### ISSUE TITLE
PCBs? 

### ISSUE THREAD

**Issue by Chr0my1702** [joelsernamoreno/EvilCrowCable-Pro#1]
Hi, will the PCBs and schematics be available? thanks :)

**Comment by joelsernamoreno** [comment]
Hello!

Because several people cloned Evil Crow RF V2 and put this for sale with a higher price, we do not provide design files

Several people bought the clone and then had problems because we do not support unofficial devices, to avoid this we had to find this solution

Evil Crow devices are already cheaply priced. You only pay for the cost of components, manufacturing and a small profit for the distributor. I have to try to keep the sales of these devices from ending up elsewhere so that I can continue to bring out low cost device

Sorry for this
